#!/usr/bin/python
# coding=utf-8

import sys

p = [[], []]

lines = sys.stdin.readlines()
lemma = sys.argv[1]

for line in lines:
    num = line.split(':')[0]
    if 'review_secrecy' in lemma:
        if 'reviewer_review_nonce' in line:
            p[0].append(num)
            continue

    if 'review_authenticity' in lemma:
        if 'reviewer_privk' in line:
            p[0].append(num)
            continue

    if 'non_transferability' in lemma:
        if 'submitter_privk' in line:
            p[0].append(num)
            continue
            
    if 'randomness_is_generated' in lemma:
        if 'randomness' in line:
            p[0].append(num)
            continue

    p[1].append(num)

for goal in [item for sublist in p for item in sublist]:
    print(goal)
